server:
 servlet:
  context-path: /cartorgon
 port: 8080
 
info:
 application:
  name: grpc-spring-boot-expl
  description: Example Application with gRPC and Spring Boot 2
  type: Spring Boot 2 gRPC micro-service
  version: 0.0.1-SNAPSHOT
 developers:
  - author:     
     name: Carlos Torres
     email: carlos.a.torres-gonzalez@capgemini.com
     role: Architect
  - author:     
     name: Carlos Torres
     email: carlos.a.torres-gonzalez@capgemini.com
     role: Backend developer
 contributors:
  - author:     
     name: Carlos Torres
     email: carlos.a.torres-gonzalez@capgemini.com
     role: Tester

management:
 endpoint:
  shutdown:
   enabled: true
 endpoints:
  beans:
   enabled: false
  web:
   base-path: /actuator
   exposure:
    include: '*'
    exclude: loggers
 security:
  enabled: false

spring:
 application:
  name: grpc-spring-boot-expl
 jmx:
  default-domain: grpc.spring.boot.expl 